# Generated by Django 4.0.4 on 2022-08-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_admin_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='logo',
            field=models.ImageField(default='/static/user.png', upload_to=''),
        ),
    ]
